import { test } from 'node:test';
import assert from 'node:assert/strict';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { createMcpServer } from '../apps/api/src/mcp-server';
import { initialProfiles, workspaceSchema } from '@jobradar/contracts';
test('MCP exposes only scoped reads and pending proposals, excluding original résumé data',async()=>{
 const snapshot=workspaceSchema.parse({revision:1,profiles:initialProfiles,tiers:{},jobs:[{id:'test',profileId:'staff',company:'Fixture',title:'Staff Frontend',location:'India',description:'Frontend scope',url:'',alignment:'review',fit:'unknown',eligibility:'unknown',createdAt:new Date().toISOString(),shortlisted:false}],resumes:[{id:'private',label:'Private',version:1,filename:'private.txt',mediaType:'text/plain',text:'PRIVATE_CONTACT_SENTINEL',sha256:'test',createdAt:new Date().toISOString()}]});
 const server=createMcpServer({read:async()=>snapshot,mutate:async()=>snapshot,close:async()=>{}});
 const client=new Client({name:'test',version:'1'});const [a,b]=InMemoryTransport.createLinkedPair();
 try{await server.connect(a);await client.connect(b);const tools=await client.listTools();assert.deepEqual(tools.tools.map(t=>t.name).sort(),['get_research_plan','get_review_packet','get_source_coverage','import_external_jobs','list_discovery_candidates','list_opportunities','list_profiles','preview_public_job_url','propose_evaluation','save_recruiter_contacts']);const plan=await client.callTool({name:'get_research_plan',arguments:{profileId:'staff'}});assert.ok(!JSON.stringify(plan).includes('PRIVATE_CONTACT_SENTINEL'));assert.match(JSON.stringify(plan),/linkedin.com/);const listing=await client.callTool({name:'list_opportunities',arguments:{profileId:'staff',limit:1}});const page=JSON.parse((listing.content as Array<{text:string}>)[0].text);assert.equal(page.total,1);assert.equal(page.nextOffset,null);assert.equal(page.jobs[0].eligibility,'unknown');assert.equal(page.jobs[0].description,'Frontend scope');assert.ok(!JSON.stringify(listing).includes('PRIVATE_CONTACT_SENTINEL'));const packet=await client.callTool({name:'get_review_packet',arguments:{jobId:'test'}});assert.ok(!JSON.stringify(packet).includes('PRIVATE_CONTACT_SENTINEL'));assert.ok(JSON.stringify(packet).includes('Frontend scope'));}finally{await client.close();await server.close();}
});
test('MCP imports deduplicate tracked URLs and refresh changed external postings with the same source',async()=>{
 const url='https://careers.example.com/jobs/1';let mutations:unknown[]=[];
 const snapshot=workspaceSchema.parse({revision:3,profiles:initialProfiles,tiers:{},jobs:[{id:'existing',profileId:'staff',company:'Example',title:'Staff Frontend',location:'India',description:'Original scope',url:url+'?utm_source=old',source:{provider:'company',board:'careers.example.com',postingId:url+'/',fetchedAt:'2026-10-05T00:00:00Z',updatedAt:null},alignment:'review',fit:'unknown',eligibility:'unknown',createdAt:'2026-10-05T00:00:00Z',shortlisted:false}]});
 const server=createMcpServer({read:async()=>snapshot,mutate:async(revision,changes)=>{assert.equal(revision,3);mutations=changes;return {...snapshot,revision:4};},close:async()=>{}});const client=new Client({name:'test-import',version:'1'});const [a,b]=InMemoryTransport.createLinkedPair();
 try{await server.connect(a);await client.connect(b);const posting={provider:'company',company:'Example',title:'Staff Frontend',location:'India',description:'Original scope',url:url+'?trk=source'};
  const first=await client.callTool({name:'import_external_jobs',arguments:{expectedRevision:3,profileId:'staff',postings:[posting]}});assert.equal(first.isError,undefined);assert.equal(JSON.parse((first.content as Array<{text:string}>)[0].text).imported,0);assert.equal(mutations.length,0);
  const next=await client.callTool({name:'import_external_jobs',arguments:{expectedRevision:3,profileId:'staff',postings:[{...posting,description:'Changed frontend responsibilities'}]}});assert.equal(next.isError,undefined);assert.equal(JSON.parse((next.content as Array<{text:string}>)[0].text).refreshed,1);assert.equal((mutations[0] as {type:string}).type,'refresh-job');assert.equal((mutations[0] as {id:string}).id,'existing');
 }finally{await client.close();await server.close();}
});
