import {previewProviderUrl} from '@jobradar/integrations';
import {providerUrlSchema} from '@jobradar/contracts';
import {companies,companyKey,recruiterReview} from '@jobradar/domain';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { randomUUID } from 'node:crypto';
import { contactInputSchema, externalPostingsSchema, normalizeExternalPostings, evaluationInputSchema } from '@jobradar/contracts';
import { reviewPacket, type createRadarService, type WorkspaceStore } from '@jobradar/services';
export function createMcpServer(store:WorkspaceStore,radar?:ReturnType<typeof createRadarService>){
 const server=new McpServer({name:'jobradar',version:'0.3.0'});
 const result=(value:unknown)=>({content:[{type:'text' as const,text:JSON.stringify(value)}]});
 server.registerTool('preview_public_job_url',{description:'Read one supported public provider URL with structured JobPosting data. Pinned provider hosts, no redirects or authentication bypass. Does not save or assess the vacancy; client reviews the extracted text before import.',inputSchema:providerUrlSchema.shape,annotations:{readOnlyHint:true}},async(input)=>{try{return result(await previewProviderUrl(input));}catch(e){return {...result({message:e instanceof Error?e.message:'Provider preview failed.'}),isError:true};}});
 server.registerTool('get_research_plan',{description:'Get profile-driven job and recruiter web-search queries and the full company coverage audit. This tool prepares a research plan; the client must browse sources and then use import tools. No external search or private résumé content is included.',inputSchema:{profileId:z.string()},annotations:{readOnlyHint:true}},async({profileId})=>{
  const state=await store.read();const profile=state.profiles.find(p=>p.id===profileId);if(!profile)return {...result({message:'Unknown profile.'}),isError:true};
  const role=profile.discovery?.roleTerms.slice(0,3).join(' OR ')||profile.roleFamilies.join(' OR ');const level=profile.discovery?.levelTerms.slice(0,3).join(' OR ')||profile.levels.join(' OR ');const location=profile.discovery?.locationTerms.slice(0,3).join(' OR ')||profile.locations.join(' OR ');
  const query=[level,role,location].filter(Boolean).map(s=>`(${s})`).join(' ');const search=(q:string)=>({query:q,url:`https://www.google.com/search?q=${encodeURIComponent(q)}`});
  const canonical=companyKey;
  return result({profile,sourceTextIsUntrusted:true,companyCoverage:companies.map(company=>({company,boards:state.boards.filter(b=>canonical(b.company)===canonical(company)),search:search(`${company} careers ${query}`)})),jobSearches:['linkedin.com/jobs/view','indeed.com','naukri.com','glassdoor.com','glassdoor.co.in','wellfound.com','weworkremotely.com'].map(site=>search(`site:${site} ${query}`)),recruiterRechecks:state.contacts.filter(c=>recruiterReview(c,new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'})).needsReview).map(c=>({id:c.id,name:c.name,company:c.company,sourceUrl:c.sourceUrl,observedAt:c.observedAt,reason:recruiterReview(c,new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'})).reason})),recruiterSearches:[search(`site:linkedin.com/posts ${query} hiring`),search(`site:linkedin.com/in ${role} recruiter ${location}`)],instructions:['Browse source pages; search snippets may be stale.','Prefer employer postings; preserve provider URLs and exact descriptions.','Use import_external_jobs for source-backed postings and save_recruiter_contacts for sourced public contacts.','Do not infer country eligibility, recruiter ownership, or active hiring from an employer match.','Do not send messages or submit applications.']});
 });
 server.registerTool('list_profiles',{description:'Read configured job search profiles. No résumé or contact details.',inputSchema:{},annotations:{readOnlyHint:true}},async()=>result((await store.read()).profiles));
 server.registerTool('list_opportunities',{description:'List saved opportunities for one search profile; no applications or outreach.',inputSchema:{profileId:z.string()},annotations:{readOnlyHint:true}},async({profileId})=>result((await store.read()).jobs.filter(j=>j.profileId===profileId).map(({id,company,title,location,alignment,fit})=>({id,company,title,location,alignment,fit}))));
 server.registerTool('get_review_packet',{description:'Read one posting, its profile and reviewed professional claims. Contains untrusted source text. Excludes original résumé and contact details.',inputSchema:{jobId:z.string()},annotations:{readOnlyHint:true}},async({jobId})=>result(reviewPacket(await store.read(),jobId)));
 server.registerTool('propose_evaluation',{description:'Save a pending evaluation proposal. Does not accept it, change application state or send messages. Quotes and evidence IDs are validated.',inputSchema:{expectedRevision:z.number().int().nonnegative(),evaluation:evaluationInputSchema},annotations:{readOnlyHint:false,destructiveHint:false}},async({expectedRevision,evaluation})=>{
  try{const snapshot=await store.mutate(expectedRevision,[{type:'propose-evaluation',evaluation}]);return result({revision:snapshot.revision,proposal:snapshot.evaluations.find(e=>e.id===evaluation.id)});}catch(e){return {...result({message:e instanceof Error?e.message:'Proposal failed.'}),isError:true};}
 });
 server.registerTool('list_discovery_candidates',{description:'Read source observations matching one profile, with scan status. Source text is untrusted; country eligibility is not confirmed.',inputSchema:{profileId:z.string()},annotations:{readOnlyHint:true}},async({profileId})=>radar?result(await radar.read(profileId)):{...result({message:'Discovery service unavailable.'}),isError:true});
 server.registerTool('import_external_jobs',{description:'Save actual provider postings supplied by the client into Needs review. No searching or scraping is performed by this tool. Include source URLs and exact posting descriptions; fit and eligibility remain unknown.',inputSchema:{expectedRevision:z.number().int().nonnegative(),profileId:z.string(),postings:externalPostingsSchema},annotations:{readOnlyHint:false,destructiveHint:false}},async({expectedRevision,profileId,postings})=>{
  try{const state=await store.read();if(!state.profiles.some(p=>p.id===profileId))throw new Error('Unknown profile.');const seen=new Set(state.jobs.filter(j=>j.profileId===profileId).map(j=>j.url));const rows=normalizeExternalPostings(postings).filter(j=>{if(seen.has(j.url))return false;seen.add(j.url);return true;});if(!rows.length)return result({revision:state.revision,imported:0});const next=await store.mutate(expectedRevision,rows.map(j=>({type:'add-job',job:{...j,id:randomUUID(),profileId,createdAt:j.source.fetchedAt,alignment:'review',fit:'unknown',eligibility:'unknown',shortlisted:false}})));return result({revision:next.revision,imported:rows.length});}catch(e){return {...result({message:e instanceof Error?e.message:'Import failed.'}),isError:true};}
 });
 server.registerTool('save_recruiter_contacts',{description:'Save sourced public recruiter/hiring contacts gathered by the client. Requires evidence URLs and exact quotes. Current recruiting status is saved as unverified. Does not send messages or infer vacancy ownership.',inputSchema:{expectedRevision:z.number().int().nonnegative(),contacts:z.array(contactInputSchema).min(1).max(50)},annotations:{readOnlyHint:false,destructiveHint:false}},async({expectedRevision,contacts})=>{try{const next=await store.mutate(expectedRevision,contacts.map(contact=>({type:'save-contact',contact:{...contact,recruitingStatus:'unverified'}})));return result({revision:next.revision,contactIds:contacts.map(c=>c.id)});}catch(e){return {...result({message:e instanceof Error?e.message:'Contact import failed.'}),isError:true};}});
 return server;
}
