'use client';
import { useState } from 'react';
import Link from 'next/link';
import { stages, type ApplicationRecord } from '@jobradar/contracts';
import { useWorkspace } from '../lib/workspace-store';
export function ApplicationTracker(){
 const {data,mutate,ready,saving,connected,error}=useWorkspace();const [selected,setSelected]=useState('');const [creating,setCreating]=useState(false);const [filter,setFilter]=useState('active');
 const list=data.applications.filter(a=>filter==='all'||!['accepted','rejected','withdrawn'].includes(a.stage)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));
 const application=list.find(a=>a.id===selected)??list[0];const currentJob=data.jobs.find(j=>j.id===application?.jobId);const originalPosting=data.postingRevisions.find(r=>r.id===application?.postingRevisionId);const job=originalPosting?.snapshot??currentJob;
 const available=data.jobs.filter(j=>!data.applications.some(a=>a.jobId===j.id));
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const get=(key:string)=>String(form.get(key)??'');
 const date=get('submittedAt');const submittedAt=!creating && application?.submittedAt?.slice(0,10)===date ? application.submittedAt : date?`${date}T12:00:00.000Z`:null;
 const common={stage:get('stage') as ApplicationRecord['stage'],resumeVersionId:get('resumeVersionId')||null,followUpAt:get('followUpAt')||null,submittedAt,note:get('note')};
 const id=creating?crypto.randomUUID():application!.id;
 const success=creating?await mutate([{type:'create-application',application:{id,jobId:get('jobId'),...common}}]):await mutate([{type:'update-application',id,...common}]);
 if(success){setSelected(id);setCreating(false);setFilter('all');}
 }
 function form(create:boolean){return <form onSubmit={save} key={create?'new':`${application!.id}:${application!.updatedAt}`}><div className="form-grid">{create&&<label>Saved job<select name="jobId" required><option value="">Choose a saved job</option>{available.map(j=><option key={j.id} value={j.id}>{j.company} · {j.title}</option>)}</select></label>}<label>Stage<select name="stage" defaultValue={create?'preparing':application!.stage}>{stages.map(stage=><option key={stage} value={stage}>{stage}</option>)}</select></label><label>Exact résumé version<select name="resumeVersionId" defaultValue={create?'':application!.resumeVersionId??''}><option value="">Unknown / not selected</option>{data.resumes.map(r=><option key={r.id} value={r.id}>{r.label} · v{r.version}</option>)}</select></label><label>Follow-up due<input name="followUpAt" type="date" defaultValue={create?'':application!.followUpAt??''}/></label><label>Actual submission date, if known<input name="submittedAt" type="date" defaultValue={create?'':application!.submittedAt?.slice(0,10)??''}/></label></div><label>Note / correction explanation<textarea name="note" rows={3} maxLength={10000}/></label><p className="fine-print">Notes append to history. Reopening, moving backwards, or correcting the résumé/submission date after applying requires an explanation. Updating a stage records your report; it does not submit an application.</p><div className="actions"><button className="button" disabled={!connected||saving} type="submit">{saving?'Saving…':create?'Create application':'Record update'}</button>{create&&<button className="text-button" type="button" onClick={()=>setCreating(false)}>Cancel</button>}</div></form>;}
 const events=data.activities.filter(event=>{const m=event.data as {id?:string;application?:{id?:string}};return ['create-application','update-application'].includes(event.type)&&(m.id===application?.id||m.application?.id===application?.id);});
 if(!ready)return <p>Loading applications…</p>;
 return <><header><div><p className="eyebrow">YOUR APPLICATION PIPELINE</p><h1>Keep every next step in view.</h1><p className="muted">Stages, follow-ups, and the résumé you actually used.</p></div><button className="button" disabled={!connected||saving||!available.length} onClick={()=>setCreating(true)}>＋ Track a job</button></header>{error&&<p className="notice" role="alert">{error}</p>}{creating?<section className="panel"><h2>Track an application</h2>{form(true)}</section>:<><div className="queue-tabs"><button aria-pressed={filter==='active'} onClick={()=>setFilter('active')}>Active</button><button aria-pressed={filter==='all'} onClick={()=>setFilter('all')}>All applications</button><span>{list.length} applications</span></div><div className="workbench-grid"><section className="job-list">{list.length?list.map(a=>{const j=data.postingRevisions.find(r=>r.id===a.postingRevisionId)?.snapshot??data.jobs.find(j=>j.id===a.jobId);return <button className={`job-row ${a.id===application?.id?'selected':''}`} key={a.id} onClick={()=>setSelected(a.id)}><div className="row-top"><strong>{j?.company}</strong><span className="tier-badge">{a.stage}</span></div><h3>{j?.title}</h3><p>{a.followUpAt?`Follow-up: ${a.followUpAt}`:'No follow-up scheduled'}</p><small className="fine-print">{a.resumeVersionId?`${data.resumes.find(r=>r.id===a.resumeVersionId)?.label} · v${data.resumes.find(r=>r.id===a.resumeVersionId)?.version}`:'Résumé version unknown / not selected'}</small></button>;}):<section className="panel empty"><h2>Start with a saved opportunity.</h2><p>Add a job, then track its application here. Closed or unsuccessful applications keep their history.</p><Link className="secondary" href="/opportunities">Open opportunities →</Link></section>}</section><section className="job-detail">{application?<><p className="eyebrow">{job?.company}</p><h2>{job?.title}</h2>{originalPosting&&<p className="fine-print">Tracked against posting version {originalPosting.version}. The original description is retained in opportunity history.</p>}{form(false)}<div className="detail-section"><h3>Activity history</h3>{events.map(event=>{const payload=event.data as {stage?:string;note?:string;application?:{stage:string;note:string}};return <article className="timeline-entry" key={event.id}><strong>{event.type==='create-application'?'Application recorded':'Update recorded'} · {payload.stage??payload.application?.stage}</strong><p>{payload.note??payload.application?.note??''}</p><small>{new Date(event.createdAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</small></article>;})}</div></>:<div className="detail-placeholder"><h2>Your application story.</h2><p>Select a record to update its stage and review the timeline.</p></div>}</section></div></>}</>;
}
