'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useWorkspace} from '../lib/workspace-store';
const api=process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000';
type Delivery={id:string;kind:string;period:string;status:string;error?:string};
type ConnectionStatus={mcp:string;emailConfigured:boolean;emailStatus?:string;providers:Record<string,string>;notificationHistory:Delivery[]};
const providerNames:Record<string,string>={linkedin:'LinkedIn',indeed:'Indeed',naukri:'Naukri',glassdoor:'Glassdoor',wellfound:'Wellfound',weworkremotely:'We Work Remotely'};
export function ConnectionsWorkspace(){
 const {data,ready}=useWorkspace();
 const [status,setStatus]=useState<ConnectionStatus>();const [error,setError]=useState('');
 const [mailNotice,setMailNotice]=useState('');const [testing,setTesting]=useState(false);const [confirmed,setConfirmed]=useState(false);
 useEffect(()=>{let live=true;fetch(`${api}/connections`).then(async r=>{if(!r.ok)throw new Error('Connection status unavailable.');return r.json();}).then(s=>{if(live)setStatus(s);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
 async function testEmail(){setTesting(true);try{const r=await fetch(`${api}/notifications/verify`,{method:'POST'});const report=await r.json();setMailNotice(report.message??'Email check completed.');}catch{setMailNotice('Email check unavailable.');}finally{setTesting(false);}}
 async function retry(id:string){try{const r=await fetch(`${api}/notifications/retry`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,providerDeliveryConfirmedAbsent:true})});const result=await r.json();setMailNotice(r.ok?'Message requeued.':result.message);if(r.ok){setConfirmed(false);const refreshed=await fetch(`${api}/connections`);if(!refreshed.ok)throw new Error();setStatus(await refreshed.json());}}catch{setMailNotice('Retry status unavailable. Check delivery history before trying again.');}}
 if(!ready)return <p role="status">Loading connections…</p>;
 const feeds=data.boards.filter(b=>['remoteok','remotive','arbeitnow','weworkremotely'].includes(b.provider));const boards=data.boards.filter(b=>!feeds.includes(b));
 const history=status?.notificationHistory??[];const pending=history.filter(n=>n.status==='pending').length;const failed=history.filter(n=>n.status==='failed').length;
 return <div className="connections-page"><header className="page-heading"><div><p className="eyebrow">SEARCH SETUP</p><h1>Connections</h1><p className="muted">Your job sources and alerts, at a glance.</p></div></header>
 {error&&<p className="notice" role="alert">{error}</p>}
 <div className="connection-grid">
 <section className="connection-card"><div className="section-heading"><h2>Job sources</h2><span className="connection-badge">Configured</span></div><p className="connection-metric"><strong>{boards.length}</strong> company boards <span>· {feeds.length} remote feeds</span></p><p>New listings appear in your discovery inbox.</p><Link className="secondary" href="/discovery">Open discovery inbox →</Link><details className="disclosure"><summary>Source coverage</summary><div className="disclosure-body"><p>Configured sources may have failed scans. Check the inbox for current run status and query limits.</p><div className="source-list">{boards.map(b=><div key={b.id}><strong>{b.company}</strong><span>{b.provider}{b.searchText?` · ${b.searchText}`:''}</span></div>)}</div><h3>Remote feeds</h3><p>{feeds.map(b=>b.company).join(' · ')}</p><p>Feeds contain listing windows; Remotive is delayed by 24 hours. India eligibility requires review.</p></div></details></section>
 <section className="connection-card"><div className="section-heading"><h2>Email alerts</h2><span className={`connection-badge ${status&&!status.emailConfigured?'attention':''}`}>{!status?'Loading':status.emailConfigured?'Needs verification':'Setup needed'}</span></div><p>{!status?'Checking email settings…':status.emailConfigured?'Email settings are saved. Verify access before checking delivery.':'Add your Gmail app password locally to enable delivery.'}</p><p className="connection-caption">Daily after 9 AM IST · Weekly on Mondays</p><details className="disclosure"><summary>Setup and delivery{failed?` · ${failed} failed`:pending?` · ${pending} queued`:''}</summary><div className="disclosure-body"><p>{status?.emailStatus??'Delivery status unavailable.'}</p><p>Set credentials in the ignored .env file, then restart the service. Local scanning and delivery need your computer running.</p><button className="secondary" disabled={testing||!status} onClick={testEmail}>{testing?'Checking…':'Test email connection'}</button><p>Checks authentication without sending an email. Receipt remains unverified until an email arrives.</p>{failed>0&&<label className="checkbox"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I checked the provider; the failed message was not delivered.</label>}<div className="delivery-list">{history.map(n=><div key={n.id}><span>{n.kind} · {n.period}</span><strong>{n.status}</strong>{n.error&&<p>{n.error}</p>}{n.status==='failed'&&<button className="secondary" disabled={!confirmed} onClick={()=>retry(n.id)}>Retry undelivered message</button>}</div>)}</div>{!history.length&&<p>No delivery records yet. Empty digests are skipped.</p>}</div></details>{mailNotice&&<p role="status" className="notice">{mailNotice}</p>}</section>
 <section className="connection-card"><div className="section-heading"><h2>Job sites</h2><span className="connection-badge neutral">Assisted search</span></div><p>LinkedIn, Indeed, Naukri, Glassdoor and Wellfound.</p><p className="connection-caption">Search and import are available. Automatic account connections are unavailable.</p><details className="disclosure"><summary>Provider details</summary><div className="disclosure-body"><div className="source-list">{status&&Object.entries(status.providers).map(([name,value])=><div key={name}><strong>{providerNames[name]??name}</strong><span>{value}</span></div>)}</div><p>Public search and reviewed imports supplement employer boards. No authenticated provider API or paid aggregator is connected.</p></div></details></section>
 <section className="connection-card"><div className="section-heading"><h2>Assistant connection</h2><span className="connection-badge neutral">{!status?'Loading':status.mcp.startsWith('Registration recorded')?'Registered':'Not registered'}</span></div><p>Use your assistant to research roles and save sourced recruiter contacts.</p><details className="disclosure"><summary>Client setup</summary><div className="disclosure-body"><p>{status?.mcp??'Connection status unavailable.'}</p><p>MCP tools were tested locally. Reload your client to load them; registration alone does not prove an active connection. The local research CLI is available as a fallback.</p></div></details></section>
 </div></div>;
}
