'use client';
import { ResumeReview } from './resume-review';
import { useState } from 'react';
import { type WorkspaceMutation } from '@jobradar/contracts';
import { useWorkspace } from '../lib/workspace-store';
const api=process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000';
export function EvidenceWorkspace(){
 const {data,mutate,uploadResume,ready,connected,saving,error}=useWorkspace();
 const [selected,setSelected]=useState('');const [mode,setMode]=useState<'upload'|'paste'|'evidence'|null>(null);const [source,setSource]=useState('resume');
 const resume=data.resumes.find(r=>r.id===selected)??data.resumes.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];
 async function addResume(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const label=String(form.get('label')).trim();let success=false;
  if(mode==='upload'){const file=form.get('file');if(file instanceof File && file.size)success=await uploadResume(file,label);}
  else success=await mutate([{type:'add-resume',id:crypto.randomUUID(),label,filename:`${label}.txt`,mediaType:'text/plain',text:String(form.get('text'))}]);
  if(success)setMode(null);
 }
 async function addEvidence(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const value=(key:string)=>String(form.get(key)??'').trim();
  const mutation:WorkspaceMutation={type:'add-evidence',evidence:{id:crypto.randomUUID(),capability:value('capability'),category:value('category'),description:value('description'),strength:value('strength') as 'exposure'|'working'|'strong'|'deep',source:source as 'resume'|'project'|'manual',resumeVersionId:source==='resume'?value('resumeVersionId'):null,quote:source==='resume'?value('quote'):'',reference:value('reference')}};
  if(await mutate([mutation]))setMode(null);
 }
 if(!ready)return <p>Loading résumé versions and evidence…</p>;
 return <><header><div><p className="eyebrow">YOUR PROFESSIONAL EVIDENCE</p><h1>Experience you can point to.</h1><p className="muted">Keep original résumés and review the claims that support your search.</p></div><div className="actions compact"><button className="button" disabled={!connected||saving} onClick={()=>setMode('upload')}>Upload résumé</button><button className="text-button" disabled={!connected||saving} onClick={()=>setMode('paste')}>Paste text</button></div></header>{error&&<p className="notice" role="alert">{error}</p>}
 {mode==='upload'||mode==='paste'?<section className="panel"><h2>{mode==='upload'?'Upload a résumé version':'Paste a résumé version'}</h2><p className="fine-print">Use the same label to create the next version. Original content is retained; existing versions are never overwritten. Processing stays on this local backend.</p><form onSubmit={addResume}><label>Version series label<input name="label" required maxLength={150} placeholder="Staff Frontend résumé"/></label>{mode==='upload'?<label className="field-space">File · PDF, TXT, or Markdown · up to 4 MB<input name="file" type="file" accept=".pdf,.txt,.md" required/></label>:<label className="field-space">Résumé text<textarea name="text" required rows={10} maxLength={100000}/></label>}<div className="actions"><button className="button" disabled={saving} type="submit">{saving?'Saving…':'Save version'}</button><button type="button" className="text-button" onClick={()=>setMode(null)}>Cancel</button></div></form></section>:null}
 {mode==='evidence'?<section className="panel"><h2>Add reviewed evidence</h2><form onSubmit={addEvidence}><div className="form-grid"><label>Capability<input name="capability" required maxLength={200} placeholder="Frontend platform migrations"/></label><label>Category<input name="category" required maxLength={100} placeholder="Architecture, SAP, leadership…"/></label><label>Strength<select name="strength"><option value="exposure">Exposure</option><option value="working">Working</option><option value="strong">Strong</option><option value="deep">Deep</option></select></label><label>Source<select value={source} onChange={e=>setSource(e.target.value)}><option value="resume">Résumé</option><option value="project">Project</option><option value="manual">Manual</option></select></label></div><label>What you did / outcome<textarea name="description" required rows={3} maxLength={5000}/></label>{source==='resume'?<><label className="field-space">Exact résumé version<select name="resumeVersionId" required defaultValue={resume?.id??''}><option value="" disabled>Select a version</option>{data.resumes.map(r=><option key={r.id} value={r.id}>{r.label} · v{r.version}</option>)}</select></label><label className="field-space">Supporting quote from that résumé<textarea name="quote" required rows={3} maxLength={5000}/></label><p className="fine-print">The backend checks that this quote exists in the selected version. Strength is your assessment; no experience is inferred automatically.</p></>:null}<label className="field-space">Additional source reference / link<input name="reference" maxLength={2000}/></label><div className="actions"><button className="button" disabled={saving} type="submit">Save evidence</button><button type="button" className="text-button" onClick={()=>setMode(null)}>Cancel</button></div></form></section>:null}
 {mode===null?<><div className="workbench-grid"><section className="job-list"><div className="group-title">Résumé versions<span>{data.resumes.length}</span></div>{data.resumes.length?data.resumes.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(r=><button className={`job-row ${resume?.id===r.id?'selected':''}`} key={r.id} onClick={()=>setSelected(r.id)}><div className="row-top"><strong>{r.label}</strong><span className="tier-badge">Version {r.version}</span></div><p>{r.filename}</p><small className="fine-print">{new Date(r.createdAt).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata'})}</small></button>):<div className="list-empty"><h2>Your résumé belongs here.</h2><p>Upload a PDF or paste text to start a versioned record.</p></div>}</section><section className="job-detail">{resume?<><p className="eyebrow">{resume.label} · VERSION {resume.version}</p><h2>Review the extracted text</h2><p className="fine-print">Extraction may lose formatting. Check this text before creating evidence. The original file is retained.</p><a className="secondary" href={`${api}/resumes/${encodeURIComponent(resume.id)}/download`}>Download original ↧</a><p className="resume-text">{resume.text}</p><p className="fine-print">Original SHA-256: {resume.sha256}</p></>:<div className="detail-placeholder"><h2>Ground your search.</h2><p>Résumé interpretation and suggested searches will come after evidence review and the ChatGPT/Codex integration.</p></div>}</section></div>{resume&&<ResumeReview key={resume.id} data={data} resumeId={resume.id} mutate={mutate} saving={saving} connected={connected}/>}<section className="panel field-space"><div className="section-heading"><div><p className="eyebrow">REVIEWED CLAIMS</p><h2>Professional evidence</h2></div><button className="button" disabled={!connected||saving} onClick={()=>setMode('evidence')}>＋ Add evidence</button></div>{data.evidence.length?data.evidence.map(item=><article key={item.id} className="evidence-row"><h3>{item.capability}<span className="tier-badge">{item.strength}</span></h3><p>{item.description}</p><p className="fine-print">{item.category} · {item.source}{item.resumeVersionId?` · ${data.resumes.find(r=>r.id===item.resumeVersionId)?.label} v${data.resumes.find(r=>r.id===item.resumeVersionId)?.version}`:''}</p>{item.quote&&<blockquote>{item.quote}</blockquote>}{item.reference&&<p className="fine-print">Source: {item.reference}</p>}</article>):<p className="muted">No reviewed evidence yet. Record capabilities and outcomes with a source; preparation work should stay separate from professional experience.</p>}</section></>:null}</>;
}
