import Link from 'next/link';
import {contactsForJob,recruiterReview} from '@jobradar/domain';
import type {WorkspaceSnapshot,OpportunityObservation} from '@jobradar/contracts';
import type {OpportunityDraft} from '@jobradar/domain';
type Job=OpportunityDraft & {source?:WorkspaceSnapshot['jobs'][number]['source']};
const providers:Record<string,string>={linkedin:'LinkedIn',indeed:'Indeed',naukri:'Naukri',glassdoor:'Glassdoor',wellfound:'Wellfound',greenhouse:'Greenhouse',lever:'Lever','lever-eu':'Lever EU',ashby:'Ashby',workable:'Workable',workday:'Workday',oracle:'Oracle Recruiting',smartrecruiters:'SmartRecruiters',rippling:'Rippling',remoteok:'Remote OK',remotive:'Remotive',arbeitnow:'Arbeitnow',weworkremotely:'We Work Remotely',company:'Company careers'};
const boards=new Set(['greenhouse','lever','lever-eu','ashby','workable','workday','oracle','smartrecruiters','rippling','company']);
function date(value:string|null|undefined){if(!value||!Number.isFinite(Date.parse(value)))return 'Not provided';return new Date(value).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'short',year:'numeric'});}
export function JobSourceFacts({job,observation}:{job:Job;observation?:OpportunityObservation}){return <><div className="job-source-label">{job.source?`${providers[job.source.provider]??job.source.provider}${boards.has(job.source.provider)?' · company board':''}`:'Manually added · source unrecorded'}</div><div className="job-dates"><span>Posted: {date(job.source?.publishedAt)}</span><span>{observation?'Last seen':job.source?'Captured':'Added'}: {date(observation?.lastSeenAt??job.source?.fetchedAt??job.createdAt)}</span></div>{!!observation?.missingCount&&<p className="job-source-warning">Absent from latest source snapshot · opening status unverified</p>}</>;}
export function JobCardMetadata({job,contacts,observation}:{job:Job;contacts:WorkspaceSnapshot['contacts'];observation?:OpportunityObservation}){
 const people=contactsForJob(job,contacts);const linked=people.filter(c=>c.jobIds.includes(job.id));const excerpt=job.description.replace(/\s+/g,' ').trim();
 return <div className="job-card-metadata"><JobSourceFacts job={job} observation={observation}/>{excerpt&&<p className="job-excerpt">{excerpt.slice(0,180)}{excerpt.length>180?'…':''}</p>}<div className="job-recruiter-summary">{people.length?<><strong>{linked.length?`${linked.length} vacancy-linked contact${linked.length===1?'':'s'}`:'Company contacts · vacancy ownership unverified'}</strong><span>{people.slice(0,2).map(c=>c.name).join(' · ')}{people.length>2?` · +${people.length-2} more`:''}</span></>:<span>Recruiter not identified</span>}</div></div>;
}
export function JobRecruiters({job,contacts}:{job:Job;contacts:WorkspaceSnapshot['contacts']}){
 const people=contactsForJob(job,contacts);const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
 return <section className="detail-section job-recruiters"><h3>Recruiters & hiring contacts</h3>{people.length?people.map(c=><article key={c.id} className="job-contact"><strong>{c.name}</strong><p>{c.title} · {c.company}</p><p className="contact-association">{c.jobIds.includes(job.id)?'Associated with this vacancy':'Company contact · vacancy ownership unverified'}</p><p>Recruiting status: {c.recruitingStatus.replaceAll('_',' ')} · {recruiterReview(c,today).reason}. Evidence observed {date(c.observedAt)}.</p><div className="contact-links"><a href={c.profileUrl} target="_blank" rel="noreferrer">Public profile ↗</a><a href={c.sourceUrl} target="_blank" rel="noreferrer">Hiring evidence ↗</a></div><details className="disclosure"><summary>Source quote & notes</summary><blockquote>{c.sourceQuote}</blockquote><p>{c.notes}</p></details></article>):<p>No sourced recruiter contact is recorded for this vacancy or company.</p>}<div className="contact-links"><Link href="/recruiters">Manage recruiter list →</Link>{!people.length&&<a href={`https://www.google.com/search?q=${encodeURIComponent(`site:linkedin.com/in ${job.company} frontend recruiter hiring`)}`} target="_blank" rel="noreferrer">Find public hiring contacts ↗</a>}</div></section>;
}
