'use client';
import {useState} from 'react';
import {normalizeExternalPostings,type WorkspaceSnapshot,type WorkspaceMutation} from '@jobradar/contracts';
export function ProviderIntake({data,profileId,mutate,saving,connected}:{data:WorkspaceSnapshot;profileId:string;mutate:(m:WorkspaceMutation[])=>Promise<boolean>;saving:boolean;connected:boolean}){
 const profile=data.profiles.find(p=>p.id===profileId);const [query,setQuery]=useState('');const [json,setJson]=useState('');const [notice,setNotice]=useState('');const terms=query||`${profile?.levels[0]??''} ${profile?.roleFamilies[0]??''} ${profile?.locations[0]??''}`;
 const sources=[['LinkedIn','linkedin','https://www.linkedin.com/jobs/search/?keywords='+encodeURIComponent(terms)],['Indeed','indeed','https://in.indeed.com/jobs?q='+encodeURIComponent(terms)],['Naukri','naukri','https://www.naukri.com/jobs-in-india?k='+encodeURIComponent(terms)],['Glassdoor','glassdoor','https://www.google.com/search?q='+encodeURIComponent('site:glassdoor.com/job-listing/ '+terms)],['Wellfound','wellfound','https://wellfound.com/remote'],['We Work Remotely','weworkremotely','https://weworkremotely.com/remote-jobs/search?term='+encodeURIComponent(terms)]];
 async function importRows(){try{const rows=normalizeExternalPostings(JSON.parse(json));const seen=new Set(data.jobs.filter(j=>j.profileId===profileId).map(j=>j.url));const unique=rows.filter(j=>{if(seen.has(j.url))return false;seen.add(j.url);return true;});if(!unique.length){setNotice('All URLs are already saved for this profile.');return;}if(await mutate(unique.map(j=>({type:'add-job',job:{...j,id:crypto.randomUUID(),profileId,alignment:'review',fit:'unknown',eligibility:'unknown',createdAt:j.source.fetchedAt,shortlisted:false}})))){setNotice(`${unique.length} sourced postings saved to Needs review. ${rows.length-unique.length} duplicate URLs skipped.`);setJson('');}}catch(e){setNotice('Import failed. Use a JSON array with provider, company, title, location, description and HTTPS posting URL. Nothing was saved.');}}
 return <section className="panel field-space" aria-label="Major provider intake"><p className="eyebrow">MAJOR JOB PROVIDERS</p><h2>Search and import sourced results</h2><p className="muted">These providers use assisted search and import. No automatic API connection is configured. Open a source, review the posting, then import its details directly or through the JobRadar MCP client.</p><label>Search terms<input value={query} placeholder={terms} onChange={e=>setQuery(e.target.value)}/></label><div className="actions field-space">{sources.map(([label,provider,url])=><a className="secondary" key={provider} href={url} target="_blank" rel="noopener noreferrer">{label} ↗</a>)}</div><details className="field-space"><summary>Import provider results as JSON</summary><p className="fine-print">Fields: provider (linkedin, indeed, naukri, glassdoor, wellfound, weworkremotely, company), company, title, location, description, url. Use actual source text. Imported jobs require fit and eligibility review. Different URLs for the same vacancy require duplicate review; they are not silently merged.</p><label>Source postings<textarea rows={10} value={json} onChange={e=>setJson(e.target.value)} placeholder={'[{"provider":"linkedin","company":"Employer","title":"Staff Frontend Engineer","location":"Bengaluru","description":"Exact posting text","url":"https://www.linkedin.com/jobs/view/POSTING_ID"}]'}/></label><button className="button" disabled={saving||!connected||!json.trim()} onClick={importRows}>Import to Needs review</button></details>{notice&&<p role="status" className="notice">{notice}</p>}</section>;
}
