'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { radarSchema, type RadarSnapshot } from '@jobradar/contracts';
import { candidateSignals, sameSource, postingContentChanged } from '@jobradar/domain';
import { useWorkspace } from '../lib/workspace-store';
const api=process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000';
const empty:RadarSnapshot={schedules:[],runs:[],inbox:[],totalInbox:0,truncated:false};
export function RadarWorkspace(){
 const {data,update,mutate,ready,saving,connected,error:workspaceError}=useWorkspace();
 const [radar,setRadar]=useState(empty);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState('');const [board,setBoard]=useState('');const [all,setAll]=useState(false);const [page,setPage]=useState(0);
 const radarPath=`/radar${all?'':`?profileId=${encodeURIComponent(data.profile)}`}`;
 async function request(path=radarPath,body?:unknown){const response=await fetch(`${api}${path}`,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);if(!response.ok){const result=await response.json();throw new Error(result.message??'Radar request failed.');}const next=radarSchema.parse(await response.json());setRadar(next);return next;}
 useEffect(()=>{let alive=true;async function refresh(){try{const response=await fetch(`${api}${radarPath}`);if(!response.ok)throw new Error('Radar backend unavailable.');const next=radarSchema.parse(await response.json());if(alive)setRadar(next);}catch(e){if(alive)setError(e instanceof Error?e.message:'Radar unavailable.');}}void refresh();const timer=setInterval(refresh,30000);return()=>{alive=false;clearInterval(timer);};},[data.profile,all]);
 useEffect(()=>setPage(0),[data.profile,all,board]);
 const profile=data.profiles.find(p=>p.id===data.profile);const criteria=profile?.discovery;
 const tier=(company:string)=>data.tiers[data.profile]?.[company.toLowerCase()]??'unclassified';
 const order=(company:string)=>({'strategic-target':0,target:1,watch:2,opportunistic:3,unclassified:4,excluded:5})[tier(company)];
 const rows=radar.inbox.filter(row=>(!board||row.boardId===board)&&(all||!!criteria&&candidateSignals(row.posting,criteria).candidate)).sort((a,b)=>order(a.posting.company)-order(b.posting.company)||b.changedAt.localeCompare(a.changedAt));
 const pages=Math.max(1,Math.ceil(rows.length/20));const current=Math.min(page,pages-1);
 async function scan(id:string){setBusy(id);setError('');setNotice('');try{await request('/radar/scan',{boardId:id,profileId:all?undefined:data.profile});setNotice('Scan complete. New and changed postings are ready for review.');}catch(e){setError(e instanceof Error?e.message:'Scan failed.');await request().catch(()=>{});}finally{setBusy('');}}
 async function schedule(event:React.FormEvent<HTMLFormElement>,boardId:string){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(boardId);setError('');try{await request('/radar/schedules',{boardId,enabled:form.get('enabled')==='on',intervalMinutes:Number(form.get('interval'))});await request();setNotice('Schedule saved. The worker must be running for automatic scans.');}catch(e){setError(e instanceof Error?e.message:'Schedule failed.');}finally{setBusy('');}}
 if(!ready)return <p>Loading discovery…</p>;
 return <><header><div><p className="eyebrow">YOUR LIVE RADAR</p><h1>A fresh inbox for your search.</h1><p className="muted">Source observations, candidate signals, and clear next steps.</p></div><Link href="/opportunities" className="secondary">Open saved opportunities →</Link></header>
 <div className="workspace-bar"><label>Search profile<select value={data.profile} onChange={e=>update(d=>({...d,profile:e.target.value}))}>{data.profiles.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Board filter<select value={board} onChange={e=>setBoard(e.target.value)}><option value="">All configured boards</option>{data.boards.map(b=><option value={b.id} key={b.id}>{b.company}</option>)}</select></label><label className="checkbox"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>Show all postings</label></div>
 {(error||workspaceError)&&<p role="alert" className="notice">{error||workspaceError}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
 {!criteria&&!all&&<p className="notice">Set discovery criteria in <Link href="/profiles">Search profiles</Link> to show profile candidates, or choose Show all postings.</p>}
 <p className="fine-print">{rows.length} observations in this view.{radar.truncated?` Showing up to 1,000 of ${radar.totalInbox} observations; narrow the profile criteria.`:''} Signals are retrieval filters, not professional-fit or eligibility assessments. Company tiers order this review inbox; saved opportunities retain their role-fit gates.</p>
 <section className="panel discovery-panel"><h2>Discovery candidates</h2>{rows.slice(current*20,(current+1)*20).map(row=>{const posting=row.posting;const existing=data.jobs.find(j=>j.profileId===data.profile&&sameSource(j.source,posting.source));const changed=!!existing&&postingContentChanged(existing,posting);return <article className="evidence-row" key={row.id}><p className="eyebrow">{posting.company} · {tier(posting.company)} · {row.change} · observation v{row.version}</p><h3>{posting.title}</h3><p>{posting.location} · Source: {posting.source.provider==='remoteok'?'Remote OK':posting.source.provider==='remotive'?'Remotive':posting.source.provider}</p>{row.missingCount>0&&<p className="notice">Not seen in {row.missingCount} successful board scan{row.missingCount===1?'':'s'}. Check the original posting before applying; closure is unconfirmed.</p>}<p className="fine-print">Last seen {new Date(row.lastSeenAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST. Presence at that time does not guarantee it is still open.</p>{criteria&&<p className="fine-print">{candidateSignals(posting,criteria).reasons.join(' ')}</p>}<div className="actions"><a className="secondary" href={posting.url} target="_blank" rel="noreferrer">Original posting ↗</a><button className="secondary" disabled={!connected||saving||!!busy||!!existing&&!changed} onClick={async()=>{const ok=existing?await mutate([{type:'refresh-job',id:existing.id,posting}]):await mutate([{type:'add-job',job:{...posting,id:crypto.randomUUID(),profileId:data.profile,createdAt:posting.source.fetchedAt,alignment:'review',fit:'unknown',eligibility:'unknown',shortlisted:false}}]);if(ok)setNotice(existing?'Updated posting retained in history; review changed scope.':'Saved to Needs review.');}}>{existing?(changed?'Accept posting update':'Already saved'):'Save for review'}</button></div><details><summary>Read responsibilities</summary><p className="description">{posting.description}</p></details></article>;})}{!rows.length&&<p>No candidates yet. Scan a company board below or broaden the configured discovery criteria.</p>}{pages>1&&<div className="discovery-pagination"><button className="secondary" disabled={!current} onClick={()=>setPage(current-1)}>Previous</button><span>Page {current+1} of {pages}</span><button className="secondary" disabled={current===pages-1} onClick={()=>setPage(current+1)}>Next</button></div>}</section>
 <section className="panel field-space"><h2>Company scans</h2><p className="fine-print">Automatic scans run while the local worker is active. Failures do not remove existing observations or close jobs.</p>{data.boards.map(b=>{const s=radar.schedules.find(s=>s.boardId===b.id);const run=radar.runs.find(r=>r.boardId===b.id);return <article className="evidence-row" key={b.id}><h3>{b.company}</h3><p>{run?`${run.status} · ${run.count} postings · ${run.newCount} new · ${run.changedCount} changed`:'Not scanned yet'}{run?.message&&` · ${run.message}`}</p><form className="toolbar" key={`${b.id}:${s?.enabled}:${s?.intervalMinutes}`} onSubmit={e=>schedule(e,b.id)}><label className="checkbox"><input name="enabled" type="checkbox" defaultChecked={s?.enabled??false}/>Automatic scans</label><label>Frequency<select name="interval" defaultValue={s?.intervalMinutes??1440}><option value={60}>Hourly</option><option value={360}>Every 6 hours</option><option value={1440}>Daily</option><option value={10080}>Weekly</option></select></label><button className="secondary" disabled={!!busy}>Save schedule</button><button className="button" type="button" disabled={!!busy} onClick={()=>scan(b.id)}>{busy===b.id?'Working…':'Scan now'}</button></form>{s?.enabled&&<p className="fine-print">Next due {new Date(s.nextRunAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</p>}</article>;})}</section>
 <details className="panel field-space"><summary>Recent scan history</summary>{radar.runs.map(run=><p className="fine-print" key={run.id}>{data.boards.find(b=>b.id===run.boardId)?.company} · {run.status} · {new Date(run.startedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} · {run.message||`${run.newCount} new, ${run.changedCount} changed`}</p>)}</details></>;
}
