'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {sourceCoverageSchema,type SourceCoverage,radarSchema,type RadarSnapshot} from '@jobradar/contracts';
import {DiscoveryPanel} from './discovery-panel';
import {useWorkspace} from '../lib/workspace-store';
const api=process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000';
const empty:RadarSnapshot={schedules:[],runs:[],inbox:[],totalInbox:0,truncated:false};
export function RadarWorkspace(){
 const {data,mutate,ready,saving,connected,error:workspaceError}=useWorkspace();
 const [coverage,setCoverage]=useState<SourceCoverage>();
 const [radar,setRadar]=useState(empty);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState('');const [board,setBoard]=useState('');
 async function request(path='/radar',body?:unknown){const response=await fetch(`${api}${path}`,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);if(!response.ok){const result=await response.json();throw new Error(result.message??'Source request failed.');}const next=radarSchema.parse(await response.json());setRadar(next);return next;}
 useEffect(()=>{let alive=true;async function refresh(){try{const response=await fetch(`${api}/radar`);if(!response.ok)throw new Error('Source status unavailable.');const next=radarSchema.parse(await response.json());if(alive)setRadar(next);const responseCoverage=await fetch(`${api}/radar/coverage`);if(!responseCoverage.ok)throw new Error('Source coverage unavailable.');const audit=sourceCoverageSchema.parse(await responseCoverage.json());if(alive){setCoverage(audit);setError('');}}catch(e){if(alive)setError(e instanceof Error?e.message:'Sources unavailable.');}}void refresh();const timer=setInterval(refresh,30000);return()=>{alive=false;clearInterval(timer);};},[]);
 async function scan(id:string){setBusy(id);setError('');setNotice('');try{await request('/radar/scan',{boardId:id});setNotice('Scan complete. Matching jobs are added automatically to Opportunities → Needs review.');}catch(e){setError(e instanceof Error?e.message:'Scan failed.');await request().catch(()=>{});}finally{setBusy('');}}
 async function schedule(event:React.FormEvent<HTMLFormElement>,boardId:string){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(boardId);setError('');try{await request('/radar/schedules',{boardId,enabled:form.get('enabled')==='on',intervalMinutes:Number(form.get('interval'))});setNotice('Schedule saved. Automatic scans run while the local worker is active.');}catch(e){setError(e instanceof Error?e.message:'Schedule failed.');}finally{setBusy('');}}
 if(!ready)return <p>Loading sources…</p>;
 return <><header><div><p className="eyebrow">SEARCH SETUP</p><h1>Sources & scans</h1><p className="muted">Configure collection here. Review discovered jobs in Opportunities.</p></div><Link className="secondary" href="/opportunities">Review opportunities →</Link></header>
 {(error||workspaceError)&&<p className="notice" role="alert">{error||workspaceError}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 {coverage&&<section className="panel source-coverage"><h2>What your radar covers</h2><p>{coverage.companyBoards} company sources · {coverage.remoteFeeds} remote feeds · {coverage.sources.filter(s=>s.enabled).length} scheduled sources</p><p>{coverage.coveredUniverseCompanies} of {coverage.universeCompanies} companies in your universe have a configured source. {coverage.sources.filter(s=>s.latestRun?.status==='failed').length} sources failed their latest scan.</p><p>{coverage.assistedProviders.join(', ')} use assisted search and import. Their full listings are not collected automatically.</p><details className="disclosure"><summary>Coverage limits & companies without sources</summary><p>Source queries collect only the keyword shown below. Remote feeds are limited windows; a remote label does not confirm India eligibility. Short descriptions may be incomplete. Saved jobs are retained when a source fails or a posting disappears.</p><p>{coverage.uncoveredCompanies.join(', ')}</p><p>Use Opportunities → Find or import additional jobs for public provider searches or imports from any company. MCP research plans prepare those searches; a connected client must actually browse and import the results.</p></details></section>}
 <section className="panel"><h2>Company boards & remote feeds · {data.boards.length}</h2><label>Source filter<select value={board} onChange={e=>setBoard(e.target.value)}><option value="">All configured sources</option>{data.boards.map(b=><option key={b.id} value={b.id}>{b.company}</option>)}</select></label><p className="fine-print">Successful scans feed every matching search profile. Fit and employment eligibility remain unverified. Failed scans do not remove jobs or confirm closure.</p>
 {data.boards.filter(b=>!board||b.id===board).map(b=>{const s=radar.schedules.find(s=>s.boardId===b.id);const run=radar.runs.find(r=>r.boardId===b.id);const stats=coverage?.sources.find(s=>s.board.id===b.id);return <details className="evidence-row source-settings" key={b.id}><summary>{b.company} · {run?.status??'Not scanned'}</summary><p>{b.provider} · {b.searchText?`Keyword scope: “${b.searchText}”`:'No source keyword filter'} · {s?.enabled?'Scheduled':'Manual scans only'}</p>{stats&&<p>{stats.observed} retained observations · {stats.missing} absent from latest source snapshot · {stats.shortDescriptions} short descriptions to check</p>}<p>{run?`${run.count} fetched · ${run.newCount} new · ${run.changedCount} changed`:'No scan recorded'}{run?.message&&` · ${run.message}`}</p><form className="toolbar" key={`${b.id}:${s?.enabled}:${s?.intervalMinutes}`} onSubmit={e=>schedule(e,b.id)}><label className="checkbox"><input name="enabled" type="checkbox" defaultChecked={s?.enabled??false}/>Automatic scans</label><label>Frequency<select name="interval" defaultValue={s?.intervalMinutes??1440}><option value={60}>Hourly</option><option value={360}>Every 6 hours</option><option value={1440}>Daily</option><option value={10080}>Weekly</option></select></label><button className="secondary" disabled={!!busy}>Save schedule</button><button className="button" type="button" disabled={!!busy} onClick={()=>scan(b.id)}>{busy===b.id?'Working…':'Scan now'}</button></form>{s?.enabled&&<p className="fine-print">Next due {new Date(s.nextRunAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</p>}</details>;})}</section>
 <details className="panel workspace-section"><summary>Add a company board or remote feed</summary><DiscoveryPanel mode="sources" data={data} mutate={mutate} saving={saving} connected={connected}/></details>
 <details className="panel workspace-section"><summary>Recent scan history</summary>{radar.runs.map(run=><p className="fine-print" key={run.id}>{data.boards.find(b=>b.id===run.boardId)?.company} · {run.status} · {new Date(run.startedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} · {run.message||`${run.newCount} new, ${run.changedCount} changed`}</p>)}</details></>;
}
