'use client';
import {useState} from 'react';
import {useWorkspace} from '../lib/workspace-store';
export function RecruiterWorkspace(){
 const {data,ready,error,saving,connected,mutate}=useWorkspace();const [query,setQuery]=useState('');const [filter,setFilter]=useState('');const [edit,setEdit]=useState('');const [notice,setNotice]=useState('');const contact=data.contacts.find(c=>c.id===edit);const profile=data.profiles.find(p=>p.id===data.profile);const search=query||`${profile?.discovery?.levelTerms[0]??profile?.levels[0]??''} ${profile?.discovery?.roleTerms[0]??profile?.roleFamilies[0]??''} recruiter ${profile?.discovery?.locationTerms[0]??profile?.locations[0]??''}`.trim();
 const visible=data.contacts.filter(c=>`${c.name} ${c.company} ${c.title} ${c.notes}`.toLowerCase().includes(filter.toLowerCase()));
 async function saveContact(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const v=(key:string)=>String(f.get(key)??'').trim();if(await mutate([{type:'save-contact',contact:{id:contact?.id??crypto.randomUUID(),name:v('name'),company:v('company'),title:v('title'),profileUrl:v('profileUrl'),sourceUrl:v('sourceUrl'),sourceQuote:v('sourceQuote'),observedAt:v('observedAt'),recruitingStatus:v('status') as 'unverified'|'recruiting'|'not_recruiting',notes:v('notes'),jobIds:f.getAll('jobIds').map(String)}}])){setEdit('');setNotice('Contact saved with its source.');form.reset();}}
 return <><header><div><p className="eyebrow">RECRUITER HUNT</p><h1>Your sourced recruiter list.</h1><p className="muted">Recruiters and public hiring contacts, with evidence and clear unknowns.</p></div></header>{error&&<p className="notice" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 <section className="panel"><h2>Discover public hiring signals</h2><label>People or hiring search<input value={query} placeholder={search} onChange={e=>setQuery(e.target.value)}/></label><div className="actions field-space"><a className="secondary" href={`https://www.google.com/search?q=${encodeURIComponent(`site:linkedin.com/in ${search} hiring`)}`} target="_blank" rel="noopener noreferrer">Search public profiles ↗</a><a className="secondary" href={`https://www.linkedin.com/search/results/content/?keywords=${encodeURIComponent(search+' hiring')}`} target="_blank" rel="noopener noreferrer">Search hiring posts ↗</a></div><p className="fine-print">Search-assisted discovery; no LinkedIn API or background scraper is connected. A connected JobRadar MCP client can save contacts it finds with source URLs and quotes. Observed date is when evidence was reviewed, not the post’s publication date. Historical signals need rechecking.</p></section>
 <section className="panel field-space"><h2>Your contacts · {data.contacts.length}</h2><label>Filter by person, company or notes<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Bangalore, React, Zyoin…"/></label>{!ready?<p>Loading…</p>:!visible.length?<p>No contacts match this view.</p>:visible.map(c=><article className="evidence-row" key={c.id}><h3>{c.name} · {c.company}</h3><p>{c.title} · {c.recruitingStatus.replaceAll('_',' ')} · evidence observed {c.observedAt}</p><blockquote>{c.sourceQuote}</blockquote><p>{c.notes}</p><div className="actions"><a className="secondary" href={c.profileUrl} target="_blank" rel="noopener noreferrer">Profile ↗</a><a className="secondary" href={c.sourceUrl} target="_blank" rel="noopener noreferrer">Hiring evidence ↗</a><button className="secondary" onClick={()=>setEdit(c.id)}>Edit contact</button></div>{!!c.jobIds.length&&<p className="fine-print">Associated opportunities: {c.jobIds.map(id=>data.jobs.find(j=>j.id===id)?.title).join(', ')}</p>}</article>)}</section>
 <section className="panel field-space"><h2>{contact?'Edit contact':'Add a sourced contact'}</h2><form key={edit||'new'} onSubmit={saveContact}><div className="form-grid">{[['name','Name'],['company','Company / hiring association'],['title','Title or unverified role label'],['profileUrl','Profile URL'],['sourceUrl','Recruiting evidence URL'],['observedAt','Evidence observed date']].map(([name,label])=><label key={name}>{label}<input name={name} required type={name.endsWith('Url')?'url':name==='observedAt'?'date':'text'} defaultValue={contact?.[name as 'name']??(name==='observedAt'?new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'}):'')}/></label>)}<label>Current recruiting status<select name="status" defaultValue={contact?.recruitingStatus??'unverified'}>{['unverified','recruiting','not_recruiting'].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Supporting source quote<textarea name="sourceQuote" required rows={3} defaultValue={contact?.sourceQuote}/></label><label>Notes · scope, source age and unknowns<textarea name="notes" rows={3} defaultValue={contact?.notes}/></label><details><summary>Associate vacancies only when ownership is supported</summary>{data.jobs.map(j=><label className="checkbox" key={j.id}><input type="checkbox" name="jobIds" value={j.id} defaultChecked={contact?.jobIds.includes(j.id)}/>{j.company} · {j.title}</label>)}</details><div className="actions field-space"><button className="button" disabled={!connected||saving}>Save contact</button>{contact&&<button type="button" className="secondary" onClick={()=>setEdit('')}>Cancel edit</button>}</div></form></section>
 {data.outreach.length>0&&<details className="panel field-space"><summary>Existing outreach history</summary>{data.outreach.map(o=><p key={o.id}>{data.contacts.find(c=>c.id===o.contactId)?.name} · {o.stage} · {o.message}</p>)}</details>}</>;
}
