'use client';
import {useState,useEffect} from 'react';
import {resumeReview,tailoringDraft} from '@jobradar/domain';
import {type WorkspaceSnapshot,type WorkspaceMutation} from '@jobradar/contracts';
export function ResumeReview({data,resumeId,mutate,saving,connected}:{data:WorkspaceSnapshot;resumeId:string;mutate:(m:WorkspaceMutation[])=>Promise<boolean>;saving:boolean;connected:boolean}){
 const [documentReport,setDocumentReport]=useState<any>();const [documentError,setDocumentError]=useState('');const [checking,setChecking]=useState(false);const [jobId,setJobId]=useState('');const [terms,setTerms]=useState('');const [draft,setDraft]=useState('');const [notice,setNotice]=useState('');useEffect(()=>{setDocumentReport(undefined);setDocumentError('');setDraft('');setNotice('');},[resumeId]);const resume=data.resumes.find(r=>r.id===resumeId);if(!resume)return null;
 const job=data.jobs.find(j=>j.id===jobId);const review=resumeReview(resume.text,job?.description??'',terms.split(','));
 return <section className="panel field-space resume-review" aria-label="Résumé ATS review"><p className="eyebrow">RÉSUMÉ ATS & REQUIREMENT REVIEW</p><h2>Check readability and job evidence</h2><p className="fine-print">Local text diagnostics and exact term matches. These checks do not predict an employer’s ATS score or prove professional fit.</p><div className="actions field-space"><button className="secondary" disabled={checking||!connected} onClick={async()=>{setChecking(true);setDocumentError('');try{const response=await fetch(`${process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000'}/resumes/${encodeURIComponent(resume.id)}/diagnostics`);const report=await response.json();if(!response.ok)throw new Error(report.message);setDocumentReport({...report,resumeId:resume.id});}catch(e){setDocumentError(e instanceof Error?e.message:'Document check failed.');}finally{setChecking(false);}}}>{checking?'Inspecting document…':'Inspect document structure'}</button></div>{documentError&&<p role="alert" className="notice">{documentError}</p>}{documentReport?.resumeId===resume.id&&<section aria-label="Document structure report"><h3>Document structure · {documentReport.format}</h3>{documentReport.pages.map((p:any)=><p key={p.number}>Page {p.number} · {p.characters.toLocaleString()} text characters · {Math.round(p.width??0)} × {Math.round(p.height??0)} points · {p.linkCount} links</p>)}{documentReport.checks.filter((c:any)=>['Text on every page','Page format'].includes(c.name)).map((c:any)=><p key={c.name}>{c.name} · {c.status}: {c.detail}</p>)}<p className="fine-print">{documentReport.limitations}</p></section>}<div className="form-grid"><label>Compare with opportunity<select value={jobId} onChange={e=>{setJobId(e.target.value);setDraft('');}}><option value="">General résumé checks</option>{data.jobs.map(j=><option key={j.id} value={j.id}>{j.company} · {j.title}</option>)}</select></label><label>Additional requirements, comma separated<input value={terms} onChange={e=>{setTerms(e.target.value);setDraft('');}} placeholder="React, accessibility, SAP Fiori" maxLength={2000}/></label></div><dl className="assessment-grid">{review.checks.map(c=><div key={c.name}><dt>{c.name} · {c.status}</dt><dd>{c.detail}</dd></div>)}</dl>{review.total>0&&<><h3>{review.matched} of {review.total} terms appear in the extracted résumé</h3><p className="fine-print">An absent term means “not found in this text”; it does not establish that you lack the experience. A present term does not prove depth.</p>{review.requirements.map(r=><details key={r.term} className="evidence-row"><summary>{r.term} · {r.inResume?'Text evidence found':'Not found'} · {r.origin}</summary>{r.jobQuote&&<><p>Posting excerpt</p><blockquote>{r.jobQuote}</blockquote></>}{r.resumeQuote&&<><p>Résumé excerpt</p><blockquote>{r.resumeQuote}</blockquote></>}</details>)}</>}
 <div className="actions field-space"><button className="secondary" disabled={!job} onClick={()=>{const result=tailoringDraft(resume.text,data.evidence,resume.id,review.requirements.map(r=>r.term));setDraft(result.text);setNotice(`${result.evidenceIds.length} exact résumé evidence excerpts selected. Review and edit the draft before saving.`);}}>Prepare tailored text draft</button></div>{notice&&<p role="status" className="notice">{notice}</p>}{draft&&<><p className="fine-print">The original chronology is preserved. Remove duplicated excerpts, check contact details and review every edit. Unsupported skills are never added automatically.</p><label>Editable tailored draft<textarea rows={16} value={draft} onChange={e=>setDraft(e.target.value)} maxLength={100000}/></label><div className="actions field-space"><button className="button" disabled={saving||!connected||!draft.trim()} onClick={async()=>{if(await mutate([{type:'add-resume',id:crypto.randomUUID(),label:`${resume.label} · ${job?.company??'tailored'}`,filename:'tailored-resume.txt',mediaType:'text/plain',text:draft}])){setDraft('');setNotice('Reviewed draft saved as a separate résumé series. Original remains available.');}}}>Save reviewed résumé version</button><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(draft);setNotice('Draft copied.');}catch{setNotice('Select and copy the draft text manually.');}}}>Copy draft</button></div></>}
 </section>;
}
