'use client';
import { useState } from 'react';
import Link from 'next/link';
import { type SearchProfile } from '@jobradar/contracts';
import { useWorkspace } from '../lib/workspace-store';
const discoveryFields=[['levelTerms','Discovery: level title terms'],['roleTerms','Discovery: role terms in title or description'],['locationTerms','Discovery: location terms'],['excludedTitleTerms','Discovery: excluded title terms']] as const;
const fields = [['roleFamilies','Role families'],['levels','Target levels'],['locations','Preferred locations'],['keywords','Discovery signals'],['exclusions','Excluded specializations']] as const;
export function SearchProfiles(){const {data,update,saveProfile,ready,saving,error,connected}=useWorkspace();const [editing,setEditing]=useState<SearchProfile>();
function newProfile(){setEditing({id:crypto.randomUUID(),name:'',version:1,roleFamilies:[],levels:[],locations:[],keywords:[],exclusions:[]});}
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const form=new FormData(e.currentTarget);const profile={...editing,name:String(form.get('name')).trim()};for(const [field] of fields)profile[field]=String(form.get(field)??'').split('\n').map(s=>s.trim()).filter(Boolean);profile.discovery={levelTerms:[],roleTerms:[],locationTerms:[],excludedTitleTerms:[]};for(const [field] of discoveryFields)profile.discovery[field]=String(form.get(field)??'').split('\n').map(s=>s.trim()).filter(Boolean);if(await saveProfile(profile))setEditing(undefined);}
if(!ready)return <p>Loading your search profiles…</p>;
return <><header><div><p className="eyebrow">CAREER DIRECTIONS</p><h1>Search profiles</h1><p className="muted">Save independent criteria for each role you want to explore.</p></div><button className="button" disabled={!connected||saving} onClick={newProfile}>＋ New profile</button></header>{error&&<p className="notice" role="alert">{error}</p>}{editing?<section className="panel"><h2>{data.profiles.some(p=>p.id===editing.id)?'Edit search profile':'New search profile'}</h2><p className="fine-print">Preferences guide discovery. They do not establish candidate qualifications. Each saved edit preserves the previous version.</p><form onSubmit={submit}><label>Profile name<input required name="name" defaultValue={editing.name} maxLength={150}/></label><div className="form-grid">{fields.map(([field,label])=><label key={field}>{label}<textarea name={field} rows={3} defaultValue={editing[field].join('\n')} placeholder="One entry per line"/></label>)}</div><h3>Candidate discovery filters</h3><p className="fine-print">Terms within a group match any term; level, role, and location groups must all match. These retrieve candidates and do not classify professional fit.</p><div className="form-grid">{discoveryFields.map(([field,label])=><label key={field}>{label}<textarea name={field} rows={3} defaultValue={editing.discovery?.[field]?.join('\n')??''} placeholder="One entry per line"/></label>)}</div><p className="fine-print">Reviewed evidence suggests these search signals: {data.evidence.map(e=>e.capability).join(', ')||'Add evidence to see suggestions.'}. Add only the signals relevant to this profile.</p><div className="actions"><button className="button" disabled={saving} type="submit">Save profile</button><button className="text-button" type="button" onClick={()=>setEditing(undefined)}>Cancel</button></div></form></section>:<div className="profile-grid">{data.profiles.map(profile=><article className="panel" key={profile.id}><p className="eyebrow">VERSION {profile.version}{data.profile===profile.id?' · ACTIVE SEARCH':''}</p><h2>{profile.name}</h2><p>{profile.roleFamilies.join(' · ')||'Role families not configured'}</p><p className="fine-print">{profile.locations.join(' · ')||'Locations not configured'}</p><div className="actions"><Link className="button" href="/opportunities" onClick={()=>update(d=>({...d,profile:profile.id}))}>Explore jobs →</Link><button className="text-button" disabled={!connected||saving} onClick={()=>setEditing(profile)}>Edit</button><button className="text-button" disabled={!connected||saving} onClick={()=>setEditing({...profile,id:crypto.randomUUID(),version:1,name:`${profile.name} — copy`})}>Duplicate</button></div></article>)}</div>}</>;}
