'use client';
import Link from 'next/link';
import { useWorkspace } from '../lib/workspace-store';
import { ApiStatus } from './api-status';
export function TodayDashboard(){const {data,ready,error}=useWorkspace();
 const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
 const active=data.applications.filter(a=>!['accepted','rejected','withdrawn'].includes(a.stage));
 const due=active.filter(a=>a.followUpAt&&a.followUpAt<=today).sort((a,b)=>a.followUpAt!.localeCompare(b.followUpAt!));
 return <><header><div><p className="eyebrow">YOUR NEXT CHAPTER</p><h1>A clearer view of your search.</h1><p className="muted">{ready?'Your records and the actions worth taking today.':'Loading your workspace…'}</p></div><ApiStatus/></header>{error&&<p role="alert" className="notice">{error}</p>}<section className="stats">{[['Saved jobs',data.jobs.length],['Active applications',active.length],['Follow-ups due',due.length]].map(([label,value])=><article key={label}><span>{label}</span><strong>{ready&&!error?value:'—'}</strong><small>From your saved records</small></article>)}</section><section className="panel"><div className="section-heading"><div><p className="eyebrow">ACTION REQUIRED</p><h2>Follow-ups due</h2></div><Link className="secondary" href="/applications">Open applications →</Link></div>{due.length?due.map(a=>{const job=data.jobs.find(j=>j.id===a.jobId);return <article className="evidence-row" key={a.id}><h3>{job?.company} · {job?.title}</h3><p>{a.followUpAt} · {a.stage}</p><Link className="secondary" href="/applications">Review and record your next step →</Link></article>;}):<p className="muted">{error?'Connect the backend to see your actions.':'No scheduled follow-ups are due. Set a date on an application to bring it here.'}</p>}</section><section className="panel field-space"><p className="eyebrow">MAKE YOUR SEARCH MORE SPECIFIC</p><h2>Start with your actual experience.</h2><p>Version your résumé and review the evidence behind your capabilities. Then track the jobs you want to pursue.</p><div className="actions"><Link className="button" href="/evidence">Add résumé & evidence →</Link><Link className="secondary" href="/opportunities">Review opportunities</Link></div></section><p className="fine-print field-space">Follow-ups use India time. This dashboard records actions; it does not send messages or apply on your behalf.</p></>;}
