'use client';
import Link from 'next/link';
import { useEffect,useState } from 'react';
import { radarSchema,workspaceAlerts,type RadarSnapshot } from '@jobradar/contracts';
import { useWorkspace } from '../lib/workspace-store';
import { ApiStatus } from './api-status';
export function TodayDashboard(){const {data,ready,error,mutate,update,saving}=useWorkspace();
 const [radar,setRadar]=useState<RadarSnapshot>();const [radarError,setRadarError]=useState('');
 useEffect(()=>{if(!ready)return;let alive=true;async function refresh(){try{const response=await fetch(`${process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000'}/radar?profileId=${encodeURIComponent(data.profile)}`);if(!response.ok)throw new Error('Discovery alerts are unavailable.');const next=radarSchema.parse(await response.json());if(alive){setRadar(next);setRadarError('');}}catch(e){if(alive)setRadarError(e instanceof Error?e.message:'Discovery unavailable.');}}setRadar(undefined);void refresh();const timer=setInterval(refresh,30000);return()=>{alive=false;clearInterval(timer);};},[ready,data.profile]);
 const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
 const alerts=workspaceAlerts(data,radar,today,data.profile);
 const active=data.applications.filter(a=>!['accepted','rejected','withdrawn'].includes(a.stage));
 const due=active.filter(a=>a.followUpAt&&a.followUpAt<=today).sort((a,b)=>a.followUpAt!.localeCompare(b.followUpAt!));
 return <><header><div><p className="eyebrow">YOUR NEXT CHAPTER</p><h1>A clearer view of your search.</h1><p className="muted">{ready?'Your records and the actions worth taking today.':'Loading your workspace…'}</p></div><ApiStatus/></header>{error&&<p role="alert" className="notice">{error}</p>}<div className="workspace-bar"><label>Search profile<select value={data.profile} onChange={e=>update(d=>({...d,profile:e.target.value}))}>{data.profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>{radarError&&<p role="alert" className="notice">{radarError}</p>}<section className="panel field-space"><h2>Action inbox · {alerts.length}</h2><p className="fine-print">New candidates are retrieval signals, not verified matches. Acknowledging a notice retains its underlying record.</p>{alerts.slice(0,20).map(a=><article key={a.id} className="evidence-row"><p>{a.message}</p><div className="actions"><Link className="secondary" href={a.href}>Review →</Link><button className="secondary" disabled={saving} onClick={()=>mutate([{type:'dismiss-alert',id:a.id}])}>Acknowledge</button></div></article>)}{alerts.length>20&&<p>{alerts.length-20} more notices. Open the discovery inbox for the full list.</p>}{!alerts.length&&<p>No pending notices for this view.</p>}</section><section className="stats field-space">{[['Saved jobs',data.jobs.length],['Active applications',active.length],['Follow-ups due',due.length]].map(([label,value])=><article key={label}><span>{label}</span><strong>{ready&&!error?value:'—'}</strong><small>From your saved records</small></article>)}</section><section className="panel"><div className="section-heading"><div><p className="eyebrow">ACTION REQUIRED</p><h2>Follow-ups due</h2></div><Link className="secondary" href="/applications">Open applications →</Link></div>{due.length?due.map(a=>{const job=data.jobs.find(j=>j.id===a.jobId);return <article className="evidence-row" key={a.id}><h3>{job?.company} · {job?.title}</h3><p>{a.followUpAt} · {a.stage}</p><Link className="secondary" href="/applications">Review and record your next step →</Link></article>;}):<p className="muted">{error?'Connect the backend to see your actions.':'No scheduled follow-ups are due. Set a date on an application to bring it here.'}</p>}</section><section className="panel field-space"><p className="eyebrow">MAKE YOUR SEARCH MORE SPECIFIC</p><h2>Start with your actual experience.</h2><p>Version your résumé and review the evidence behind your capabilities. Then track the jobs you want to pursue.</p><div className="actions"><Link className="button" href="/evidence">Add résumé & evidence →</Link><Link className="secondary" href="/opportunities">Review opportunities</Link></div></section><p className="fine-print field-space">Follow-ups use India time. This dashboard records actions; it does not send messages or apply on your behalf.</p></>;}
